name: Checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: |
        pip install --upgrade pip
        pip install black==21.6b0 pylint==v3.0.0a3 mypy==v0.902 types-requests==2.25.0
    - run: black --diff --check jsonrpcclient
    - run: pylint --disable=all --enable=unused-import jsonrpcclient
    - run: mypy --disallow-untyped-defs --disallow-untyped-calls --check-untyped-defs jsonrpcclient
